--CREATE DATABASE IF NOT EXISTS REBOOT;
DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE IF NOT EXISTS EMPLOYEE
(
    ID            INT         NOT NULL AUTO_INCREMENT,
    NAME          VARCHAR(45) NOT NULL,
    MIDDLE_NAME    VARCHAR(45) NULL,
    LAST_NAME      VARCHAR(45) NOT NULL,
    MOTHER_SUR_NAME VARCHAR(45) NOT NULL,
    AGE           INT         NOT NULL,
    GENDER        VARCHAR(1)  NOT NULL,
    BIRTH_DATE     DATE        NOT NULL,
    POSITION      VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID)
);
